---
- debug:
    var: zfsprep_efi|default(false)|bool == true

- name: ln -s /proc/self/mounts /etc/mtab
  file:
    src: /proc/self/mounts
    dest: /etc/mtab
    state: link

- name: install locales package
  apt:
    update_cache: yes
    name: locales
    state: present

- name: install locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ zfsprep_locales }}"

- name: set LANG in /etc/default/locale
  lineinfile:
    line: "LANG={{ zfsprep_lang }}"
    path: /etc/default/locale
    insertafter: EOF

- name: set timezone
  timezone:
    name: "{{ zfsprep_timezone }}"

- name: reconfigure tzdata package
  command: dpkg-reconfigure -f noninteractive tzdata

- name: install dpkg-dev, kernel and headers
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - dpkg-dev
      - "{{ zfsprep_kernel_package }}"
      - "{{ zfsprep_headers_package }}"
      - zfs-initramfs

- name: install grub-pc
  apt:
    name: grub-pc
    state: present
  when: zfsprep_efi|default(false)|bool != true

- name: install dosfstools
  apt:
    name: dosfstools
    state: present
  when: zfsprep_efi|default(false)|bool == true

- name: set up grub partitions for efi
  command: "mkdosfs -F32 -n EFI {{ item }}"
  with_items:
    - "{{ zfsprep_efi_partition }}"
  when: zfsprep_efi|default(false)|bool == true

- name: create efi mountpoint
  file:
    path: /boot/efi
    state: directory
  when: zfsprep_efi|default(false)|bool == true

- name: get efi partition uuid
  command: "blkid -s PARTUUID -o value {{ disk }}"
  register: efi_blkid
  vars:
    disk: "{{ zfsprep_efi_partition | first }}"
  when: zfsprep_efi|default(false)|bool == true

- name: update fstab with efi partition
  mount:
    path: /boot/efi
    src: PARTUUID={{ efi_blkid.stdout }}
    fstype: vfat
    opts: nofail,x-systemd.device-timeout=1
    dump: 0
    passno: 1
    state: mounted
  when: zfsprep_efi|default(false)|bool == true

- name: update fstab entry for boot volume
  mount:
    path: /boot
    src: "{{ zfsprep_boot_pool }}/BOOT/debian"
    fstype: zfs
    opts: nodev,relatime,x-systemd.requires=zfs-import-bpool.service
    dump: 0
    passno: 0
    state: present

# - name: update fstab entries for select root pool volumes
#   mount:
#     path: "{{ item }}"
#     src: "{{ zfsprep_root_pool }}{{ item }}"
#     fstype: zfs
#     opts: defaults
#     dump: 0
#     passno: 0
#     state: present
#   with_items:
#     - /tmp
#     - /var/log
#     - /var/spool
#     - /var/tmp

- name: get backup efi partition uuid
  command: "blkid -s PARTUUID -o value {{ item }}"
  register: efi_backup_blkid
  with_items:
    - "{{ zfsprep_efi_partition[1:] }}"
  when: zfsprep_efi|default(false)|bool == true

- name: update fstab with backup efi partitions
  mount:
    path: /boot/efi
    src: PARTUUID={{ item.stdout }}
    fstype: vfat
    opts: noauto,nofail,x-systemd.device-timeout=1
    dump: 0
    passno: 1
    state: present
  when: zfsprep_efi|default(false)|bool == true
  loop: "{{ efi_backup_blkid.results }}"

- name: install grub-efi-amd64 and shim-signed
  apt:
    name: ['grub-efi-amd64', 'shim-signed']
    state: present
  when: zfsprep_efi|default(false)|bool == true

- name: set root password
  user:
    name: root
    password: "{{ zfsprep_root_password_hash }}"

- name: create swap zvol
  zfs:
    name: "{{ zfsprep_root_pool }}/swap "
    state: present
    extra_zfs_properties:
      "{{ zfsprep_swap_opts }}"

- name: mkswap
  command: "mkswap -f /dev/zvol/{{ zfsprep_root_pool }}/swap"
  when: zfsprep_swap|default(false)|bool == true

- name: write swap entry in fstab
  mount:
    backup: yes
    path: none
    src: "/dev/zvol/{{ zfsprep_root_pool }}/swap"
    fstype: swap
    opts: defaults
    passno: 0
    dump: 0
    state: present
  when: zfsprep_swap|default(false)|bool == true

- name: swapon
  command: swapon -av
  when: zfsprep_swap|default(false)|bool == true

- lineinfile:
    line: "RESUME=none"
    path: /etc/initramfs-tools/conf.d/resume
    create: yes
    state: present
  when: zfsprep_swap|default(false)|bool == true

- name: update initramfs
  command: "update-initramfs -u -k all"

- name: modify /etc/default/grub
  replace:
    path: /etc/default/grub
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  with_items:
    - regex: "^(GRUB_HIDDEN_TIMEOUT.*)"
      replace: "#\\1"
    - regex: "^GRUB_CMDLINE_LINUX_DEFAULT=.*"
      replace: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
    - regex: "^GRUB_CMDLINE_LINUX=.*"
      replace: 'GRUB_CMDLINE_LINUX="{{ zfsprep_grub_cmdline }}"'
    - regex: "^#(GRUB_TERMINAL.*)"
      replace: "\\1"

- name: update grub
  command: update-grub

- name: grub install
  command: "grub-install {{ item }}"
  with_items:
    - "{{ zfsprep_root_device_list }}"
  when: zfsprep_efi|default(false)|bool != true

- name: install grub efi on primary disk
  command: "grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=debian --recheck --no-floppy"
  when: zfsprep_efi|default(false)|bool == true

- name: unmount boot efi partition
  mount:
    path: /boot/efi
    state: unmounted

- name: write grub boot sector
  command: "dd if={{ zfsprep_efi_partition | first }} of={{ item }}"
  with_items:
    - "{{ zfsprep_efi_partition[1:] }}"
  when: (zfsprep_efi|default(false)|bool == true) and (zfsprep_root_device_list | length > 1)

- name: setup efi on secondary disks
  command: "efibootmgr -c -g -d {{ item.0 }} -p 3 -L 'debian-{{ item.1 }}' -l '\\EFI\\debian\\grubx64.efi'"
  with_together:
    - "{{ (zfsprep_root_device_list | map('regex_replace', '(.*)', '\\g<1>') | list)[1:] }}"
    - "{{ zfsprep_root_disks[1:] }}"
  when: (zfsprep_efi|default(false)|bool == true) and (zfsprep_root_device_list | length > 1)

- name: set mountpoint=legacy for boot pool
  command: "zfs set mountpoint=legacy {{ zfsprep_boot_pool }}/BOOT/debian"

- name: make zfs-list.cache directory
  file:
    path: /etc/zfs/zfs-list.cache
    state: directory

- name: create root pool list
  file:
    path: "/etc/zfs/zfs-list.cache/{{ zfsprep_root_pool }}"
    state: touch
    mode: u+r,g+r,o+rw

- name: enable zed.d
  file:
    src: /usr/lib/zfs-linux/zed.d/history_event-zfs-list-cacher.sh
    dest: /etc/zfs/zed.d/history_event-zfs-list-cacher.sh
    state: link

- name: run zed to update zfs list cache
  shell: "nohup zed -F > /dev/null 2>&1 &"

- name: change root pool zfs property to force cache update
  command: "zfs set canmount=noauto {{ zfsprep_root_pool }}/ROOT/debian"

- name: pause for 30 seconds to give zed time to write list cache
  pause:
    seconds: 30

- name: get PID for zed so we can kill it
  command: "pgrep zed"
  register: zed_pid

- name: kill zed
  shell: "kill {{ zed_pid.stdout }}"

- name: fix paths in zfs list cache for root pool
  command: "sed -Ei \"s|/mnt/?|/|\" /etc/zfs/zfs-list.cache/{{ zfsprep_root_pool }}"

- name: mount boot efi partition
  command: mount /boot/efi

- name: ensure zfs.target starts on boot
  systemd:
    name: zfs.target
    enabled: yes

- name: install zfs-import-bpool.service
  template:
    src: zfs-import-bpool.j2
    dest: /lib/systemd/system/zfs-import-bpool.service
    mode: 0644

- name: enable zfs-import-bpool service
  systemd:
    name: zfs-import-bpool.service
    enabled: yes

- name: install firstboot service
  template:
    src: firstboot.service.j2
    dest: /lib/systemd/system/firstboot.service

- name: install firstboot script
  template:
    src: firstboot.j2
    dest: /opt/firstboot
    mode: 0777

- name: enable firstboot service
  systemd:
    name: firstboot.service
    enabled: yes

#- name: enable systemd-networkd service
#  systemd:
#    name: systemd-networkd
#    enabled: yes
