- hosts: live
  vars_files:
    - vars.yml
  tasks:
    - name: import pre-chroot tasks
      import_tasks: pre-chroot.yml
- hosts: chroot
  gather_facts: no
  tasks:
    - name: make sure python is installed in our chroot
      raw: "apt-get update && apt-get -y install python"
- hosts: chroot
  vars_files:
    - vars.yml
  tasks:
    - name: import chroot tasks
      import_tasks: chroot.yml
    - name: import post-build tasks
      import_tasks: post.yml
