- hosts: live
  vars_files:
    - vars/common.yml
    - playbook-vars.yml
  tasks:
    - name: pre-chroot tasks
      import_tasks: tasks/pre-chroot.yml
- hosts: chroot
  gather_facts: no
  tasks:
    - name: make sure python is installed in our chroot
      raw: "apt-get update && apt-get -y install python3"
- hosts: chroot
  vars_files:
    - vars/common.yml
    - playbook-vars.yml
  tasks:
    - name: chroot tasks
      import_tasks: tasks/chroot.yml
    - name: post-build tasks
      import_tasks: tasks/post.yml
