---
# defaults file for 02-chroot
zfsprep_efi: true
zfsprep_swap: true
zfsprep_swap_opts:
  volsize: 4G
  compression: zle
  logbias: throughput
  sync: always
  primarycache: metadata
  secondarycache: none
  com.sun:auto-snapshot: false
zfsprep_timezone: "UTC"
zfsprep_boot_pool: bpool
zfsprep_root_pool: rpool
zfsprep_grub_cmdline: "root=ZFS={{ zfsprep_root_pool }}/ROOT/debian"
zfsprep_root_disks_by_id: "{{ zfsprep_root_disks | map('extract', hostvars[inventory_hostname]['ansible_devices'], ['links', 'ids', 0]) | list | map('regex_replace', '(.*)', '/dev/disk/by-id/\\g<1>') | list }}"
zfsprep_root_device_list: "{{ zfsprep_legacy_device_nodes | ternary((zfsprep_root_disks | map('regex_replace', '(.*)', '/dev/\\g<1>') | list), zfsprep_root_disks_by_id) }}"
zfsprep_legacy_device_nodes: false
zfsprep_efi_part_append: "{{ zfsprep_legacy_device_nodes | ternary('1', '-part1') }}"
zfsprep_boot_part_append: "{{ zfsprep_legacy_device_nodes | ternary('2', '-part2') }}"
zfsprep_root_part_append: "{{ zfsprep_legacy_device_nodes | ternary('3', '-part3') }}"
zfsprep_efi_partition: "{{ zfsprep_root_device_list | map('regex_replace', '(.*)', '\\g<1>' + zfsprep_efi_part_append) | list }}"
zfsprep_extra_locales: []
zfsprep_lang: "en_US.UTF-8"
zfsprep_locales: "{{ zfsprep_extra_locales + [zfsprep_lang] }}"
zfsprep_kernel_package: "linux-image-amd64"
zfsprep_headers_package: "linux-headers-amd64"
zfsprep_root_password_hash: "$6$TwdlMzLJ6B$qqj/8soZa5eURXAa54wkjneV5VZG4r664A3VbSrcl4upJwSiiH4o78uTXRhLPwQJP7mXpKShr849mCAs24lTX/" # "vagrant"
